---
abstract: 'Interface to vFeed Open Source Cross Linked and Aggregated Local Vulnerability Database'
author:
  - 'GomoR <gomor-cpan_at_gomor.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.132510'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: vFeed
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Tar: 0
  Class::Gomor: 0
  DBI: 0
  Digest::SHA1: 0
  LWP::UserAgent: 0
  perl: 5.006001
version: 0.12
